name: Build Backend
on:
  push:
    branches: [anuja]
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: pip install -r clinic_project/requirements.txt
      - name: Build Backend
        run: python clinic_project/manage.py test
